INPUT_PROMT = "~> "
SPECIAL_PROMT = ":> "
UNKNOWN_COMMAND_MESSAGE = "Unknown Command"

SESSION_TOKEN = "{}/"
DEFAULT_DATA_DIR = "data/"
SESSION_DIR = DEFAULT_DATA_DIR + "session/"
DEFAULT_SESSION_DIR_TEMPLATE = SESSION_DIR + SESSION_TOKEN
DEFAULT_SESSION_DIR = "NotExists"
DEFAULT_USER_DIR = "user/"
DEFAULT_USER_DATA_FILE = DEFAULT_USER_DIR + "user_data.pckl"
DEFAULT_USER_START_MONEY = 1_000

DEFAULT_MARKET_DIR = "market/"
DEFAULT_MARKET_DATA_FILE = DEFAULT_MARKET_DIR + "market_data.pckl"

GLOBAL_USER_NAME = "user"
GLOBAL_MARKET_NAME = "market"
GLOBAL_SESSION_NAME = "session"
